version: '3.7'

services:

  mongo:
    image: mongo:4.2.1
    ports:
    - 27018:27017
    networks:
    - backend

  app-server:
    image: api-allcinemas123
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/allcinemas_test
    ports:
    - 8081:8080
    depends_on:
    - mongo
    restart: always
    networks:
    - backend

networks:
  backend:
